//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML
//  @ File Name : Eleve.h
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#if !defined(_ELEVE_H)
#define _ELEVE_H

#include "Prof.h"

class Eleve {
private:
	string _Nom;
	string _Prenom;
	int _Age;
	int _Promotion;
	Prof _Tuteur;
	double _MoyenneGene;
public:

	Eleve();
	~Eleve();

	friend ostream & operator<<(ostream & os, const Eleve & e);
	friend istream & operator>>(istream & is, const Eleve & e);
};

#endif  //_ELEVE_H
