//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML 
//  @ File Name : MembreAdmin.cpp
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#include "MembreAdmin.h"

void MembreAdmin::InscriptionProf(int Prof, int Module) {

}

void MembreAdmin::InscriptionEleve(int Eleve, int Module) {

}

void MembreAdmin::AffectationProfModule(int Prof, int Module) {

}

void MembreAdmin::AffectationProfTuteur(int Prof, int Eleve) {

}

