//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML 
//  @ File Name : MembreAdmin.h
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#if !defined(_MEMBREADMIN_H)
#define _MEMBREADMIN_H


class MembreAdmin {
public:
	void InscriptionProf(int Prof, int Module);
	void InscriptionEleve(int Eleve, int Module);
	void AffectationProfModule(int Prof, int Module);
	void AffectationProfTuteur(int Prof, int Eleve);
};

#endif  //_MEMBREADMIN_H
