//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML
//  @ File Name : Module.h
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#if !defined(_MODULE_H)
#define _MODULE_H


class Module {
public:
    Module(double _PondCE = 0.2, double _PondDE = 0.5, double _PondPROJET = 0.2, double _PondTP = 0.1);
private:
	prof _ProfesseurResponsable;
	eleve _TAB_Eleve;
	prof _TabAssistant;
	double _PondCE;
	double _PondDE;
	double _PondPROJET;
	double _PondTP;
};

#endif  //_MODULE_H
