//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML
//  @ File Name : Note.h
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#if !defined(_NOTE_H)
#define _NOTE_H


class Note {
public:
    Note(double _CE = 0, double _DE = 0, double _PROJET = 0, double _TP = 0);

	void ajoutnote();
	double CalculMoyenne(double, double, double, double, double, double, double, double);

	friend ostream & operator<< (ostream & os, const Note & n);
	friend istream & operator>> (istream & is, const Note & n);

private:
    double _CE;
	double _DE;
	double _PROJET;
	double _TP;


};

#endif  //_NOTE_H
