//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML
//  @ File Name : Prof.h
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#if !defined(_PROF_H)
#define _PROF_H

#include "Module.h"

class Prof {
private:
    string _Nom;
    string _Prenom;
    int _Age;
	Module _Professeur;
	Module _Assistant;

public:

    Prof();
	void ReceptionAlerteEleveSeuil10();
	void AjoutNote(int Eleve, int Note, int Module);
	void MAJNote(int Eleve, int Note, int Module);
};

#endif  //_PROF_H
