//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML
//  @ File Name : Prof.cpp
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#include "Prof.h"


Prof::Prof(string Nom, string Prenom, int Age): _Nom(Nom), _Prenom(Prenom), _Age(Age)
{

}

ostream & operator<<(ostream & os, const Prof & p)
{
    os << "Nom : " << p._Nom << endl
    << "Prenom : " << p._Prenom << endl
    << "Age : " << p._Age << endl
    << "Professeur du module : " << p._Professeur << endl
    << "Assistant du module : " << p._Assistant <<endl;

    return os;
}

istream & operator>>(istream & is, const Prof & p)
{
    is >> p._Nom;
    is >> p._Prenom;
    is >> p._Age;
    is >> p._Professeur;
    is >> p._Assistant;

    return is;
}

void Prof::ReceptionAlerteEleveSeuil10() {

}

void Prof::AjoutNote(int Eleve, int Note, int Module) {

}

void Prof::MAJNote(int Eleve, int Note, int Module) {

}


