//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet UML 
//  @ File Name : Specialite.h
//  @ Date : 08/04/2014
//  @ Author : Matteo Gulino & Paul Maupas
//
//


#if !defined(_SPECIALITE_H)
#define _SPECIALITE_H

#include "Module.h"

class Specialite {
public:
	Module TAB_Module;
};

#endif  //_SPECIALITE_H
